feat(cfp): adjust cfp with new design
bandungpy/pycon.id pull request #36
Opened 2023-08-01 08:36 UTC by jeeehaan

2023-08-01 10:40 UTC, ridhof requested changes

2023-08-01 10:40 UTC, ridhof commented on app/routes/cfp._index.tsx
> +                href="https://drive.google.com/file/d/1Xcn9GyAFnlVk7Yhxu1Xx77V2T2u4LLMj/view?usp=sharing"
it's not the correct url, please keep papercall io as the href

2023-08-01 10:40 UTC, ridhof commented on app/routes/cfp._index.tsx
> +            <p className="text-xl text-primary md:text-4xl lg:text-2xl">
please use the same font styling with sponsorship page, because the font size doesn't look the same

2023-08-03 15:13 UTC, jeeehaan commented
Mas @ridhof, I would like to request a review of my latest push. I just added responsiveness to the page, could you please take some time to review the updates?

2023-08-03 21:00 UTC, ridhof requested changes

2023-08-03 21:03 UTC, ridhof commented
lgtm

responsiveness looks good, please solve request changes I mentioned above and then you can merge this PR

2023-08-04 04:27 UTC, jeeehaan commented
Hi mas @ridhof, i've solved the request you mentioned above, but my merge button is currently blocked. Could you help me merge my PR?

2023-08-04 06:02 UTC, ridhof approved these changes
LGTM

2023-08-04 06:03 UTC, merged